[package]
name = "galoy-bitcoin"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0", features = ["derive", "env"] }
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
