[package]
name = "bria"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0", features = ["derive", "env"] }
chrono = { version = "0.4.22", features = ["clock", "serde"], default-features = false }
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
sqlx = { version = "0.6", features = [ "offline", "runtime-tokio-rustls", "postgres", "decimal", "uuid", "chrono"] }
sqlxmq = { version = "0.4.1", default-features = false, features = [ "runtime-tokio-rustls" ] }
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }
tonic = "0.8"
rust_decimal = "1.25.0"
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
prost = "0.11"
rust_decimal_macros = "1.26.1"
rusty-money = "0.4.1"
thiserror = "1.0.37"
uuid = { version = "1.2.1", features = ["serde", "v4"] }
futures = "0.3.25"
url = "2.3.1"
rand = "0.8.5"

[build-dependencies]
protobuf-src = { version = "1.1.0" }
tonic-build = { version = "0.8", features = ["prost"] }
