version: "3"
services:
  e2e-deps:
    image: busybox
    depends_on:
      - postgres
      - bitcoind
      - lnd
      - otel-agent
      - fulcrum
  integration-deps:
    image: busybox
    depends_on:
      - postgres
      - bitcoind
      - lnd
      - otel-agent
      - fulcrum
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  e2e-tests:
    image: us.gcr.io/galoy-org/rust-concourse
    depends_on:
      - e2e-deps
    command: [ "make", "e2e-tests-in-container" ]
    working_dir: /repo
    volumes:
      - ./:/repo
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BRIA_CONFIG=docker
      - RUST_LOG=error
      - DATABASE_URL=postgres://user:password@postgres:5432/pg
      - PG_CON=postgres://user:password@postgres:5432/pg
      - PG_HOST=postgres
      - BITCOIND_HOST=bitcoind
      - LND_HOST=lnd
      - ELECTRUM_HOST=fulcrum
  integration-tests:
    image: us.gcr.io/galoy-org/rust-concourse
    depends_on:
      - integration-deps
    command: [ "make", "integration-tests-in-container" ]
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/pg
      - PG_HOST=postgres
      - BITCOIND_HOST=bitcoind
      - LND_HOST=lnd
      - ELECTRUM_HOST=fulcrum
    working_dir: /repo
    volumes:
      - ./:/repo
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.57.2
    command: [ "--config=/etc/otel-agent-config.yaml" ]
    environment:
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml
  bitcoind:
    image: lncm/bitcoind:v24.0.1
    volumes:
      - ${PWD}/dev/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
  lnd:
    image: lightninglabs/lnd:v0.15.4-beta
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd.wallet.db:/root/.lnd/wallet.db
      - ${PWD}/dev/lnd/regtest/lnd.macaroons.db:/root/.lnd/macaroons.db
      - ${PWD}/dev/lnd/regtest/lnd.admin.macaroon:/root/.lnd/admin.macaroon
    depends_on: [ bitcoind ]
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        mkdir -p /root/.lnd/data/chain/bitcoin/regtest/
        cp /root/.lnd/wallet.db /root/.lnd/data/chain/bitcoin/regtest/wallet.db
        cp /root/.lnd/macaroons.db /root/.lnd/data/chain/bitcoin/regtest/macaroons.db
        cp /root/.lnd/admin.macaroon /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
        /bin/lnd
  fulcrum:
    image: cculianu/fulcrum:latest
    depends_on: [ bitcoind ]
    volumes:
      - ${PWD}/dev/fulcrum/fulcrum.conf:/fulcrum.conf
      - ${PWD}/dev/fulcrum/tls.key:/tls.key
      - ${PWD}/dev/fulcrum/tls.cert:/tls.cert
    environment:
      - DATA_DIR=/db
      - SSL_CERTFILE=/tls.cert
      - SSL_KEYFILE=/tls.key
    command: [ "Fulcrum", "/fulcrum.conf" ]
