name: "E2E Tests"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: End to End Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0
      - name: Install protoc dependencies for prost-wkt-types
        run: sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions/checkout@v3
      - name: Setup cache for cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-wiped
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run e2e tests
        env:
          PG_CON: postgres://user:password@127.0.0.1:5432/pg
        run: make e2e
